### ISSUE TITLE
Which version should I use?

### ISSUE THREAD

**Issue by mariovillamizar** [fuzzylite/pyfuzzylite#4]
Hi @jcrada. Thanks for this great library and your effort.
I have a question.. I installed the library using pip install pyfuzzylite following the instructions here https://pypi.org/project/pyfuzzylite/ (The page says that the command will install the version 7.0b3). Then I tried to run an example but I got a lot of errors. That’s because the example was not matching the constructors of the installed version.
I went to the repository and your last release was the version 7.0b2 which is matching with the examples.
That’s confusing, so I want to ask you: which version should I use?

Thanks again.

**Comment by jcrada** [comment]
Hi Mario, thanks for your kind words.

I apologise for the misunderstanding in the versioning. I have created a release 7.0b3 in github: https://github.com/fuzzylite/pyfuzzylite/releases/tag/7.0b3

Alternatively, you should be able to do from console: `pip3 install pyfuzzylite`, which will get you 7.0b3
