### ISSUE TITLE
__init__() got an unexpected keyword argument 'xxxxxxxxx'  error in PyFuzzyLite

### ISSUE THREAD

**Issue by cgarzon777** [fuzzylite/pyfuzzylite#5]
From QTFuzzyLite to FuzzyLite to C++ and then to Python under Windows10 there was no problem.
Everything ran smoothly 
When downloaded to RaspberryPi3 B + under Raspbian BUster , Python 7 and pyFuzzyLite I encounter the following errors:

__init__() got an unexpected keyword argument 'xxxxxxxxx'
fl.engine.input_variables does not take arguments

Specifically under two arguments:
enable and Lock_range

I used the Thonny Pyton and Spyder 3 programs on raspberry pi with the same error in both.
Both have the pyFuzzyLite packages up to date.

Please find the file attached

[SmartDimmer.txt](https://github.com/fuzzylite/pyfuzzylite/files/4593551/SmartDimmer.txt)

**Comment by jcrada** [comment]
Hi, I strongly suggest you use PyCharm for Python development. There you will see that you have mistakes on SmartDimmer.txt. Specifically, you need to replace: 

* `fl.AlgebraicProduct` for `fl.AlgebraicProduct()`; and 
* `fl.AlgebraicSum` for `fl.AlgebraicSum()`. 

In addition, you could use PyCharm debugging options to find out about errors.

![Uploading Screen Shot 2020-05-10 at 22.07.28.png…]()

Thanks
