### ISSUE TITLE
Questions to create a TSK model

### ISSUE THREAD

**Issue by ManStu** [fuzzylite/pyfuzzylite#75]
I have questions about creating Takagi-Sugeno-Kang fuzzy models:
I adapted the example fuzzylite/examples/takagi_sugeno/obstacle_avoidance.py as follows:

import fuzzylite as fl

class ObstacleAvoidance:
    def __init__(self) -> None:
        self.engine = fl.Engine(
            name="ObstacleAvoidance",
            input_variables=[
                fl.InputVariable(
                    name="obstacle",
                    minimum=0.0,
                    maximum=1.0,
                    lock_range=False,
                    terms=[fl.Ramp("left", 1.0, 0.0), fl.Ramp("right", 0.0, 1.0)],
                ),
                fl.InputVariable(
                    name="obstacle2",
                    minimum=0.0,
                    maximum=1.0,
                    lock_range=False,
                    terms=[fl.Ramp("left", 1.0, 0.0), fl.Ramp("right", 0.0, 1.0)],
                )
            ],
            output_variables=[
                fl.OutputVariable(
                    name="tsSteer",
                    minimum=0.0,
                    maximum=1.0,
                    lock_range=False,
                    lock_previous=False,
                    default_value=fl.nan,
                    aggregation=fl.Maximum(),
                    defuzzifier=fl.WeightedAverage(),
                    terms=[
                        fl.Linear("right", [1, 1, 1]),
                        fl.Linear("left", [1, 1, 1]),
                    ]
                )
            ],
            rule_blocks=[
                fl.RuleBlock(
                    name="takagiSugeno",
                    conjunction=fl.Minimum(),
                    disjunction=None,
                    implication=None,
                    activation=fl.General(),
                    rules=[
                        fl.Rule.create("if obstacle is left and obstacle2 is left then tsSteer is right"),
                        fl.Rule.create("if obstacle is left and obstacle2 is right then tsSteer is left"),
                    ],
                )
            ],
        )
        

if __name__ == '__main__':
    test = ObstacleAvoidance()
    engine = test.engine

    obstacle_var = engine.input_variables[0]
    obstacle_var.value = 0.2
    engine.process()

    out_var = engine.output_variables[0]
    print(out_var.value)

---------------
My questions:
• Why is an array returned instead of a value?
• Why are the values ​​of the array nan?
In my view, a single value that is not nan would have to be delivered.

Thanks for your support!

**Comment by jcrada** [comment]
Hi

Thanks for your post. 

(1) Numpy is now used across the library, and its main component is the array (`np.array`), but you should be getting a unit array, ie with a single value. 

(2) I think the nan values are because you set the input value of only one input variable when you have two. The default input value is nan, which propagates. If you set the other variable's value you should see what you expect.  

Let me know if this solves your issues. 

Cheers

**Comment by ManStu** [comment]
Hi,

thank you very much for the quick reply. A funny mistake that I only assigned a value to one variable. The tip helps.

However, the model returns an array whose length is equal to the number of model input variables. The optional constant has no effect on the length.
The input variables taken into account in the premises also have no influence on the array.


Regards
Manfred

Von: Juan Rada-Vilela ***@***.***>
Gesendet: Freitag, 19. April 2024 00:02
An: fuzzylite/pyfuzzylite ***@***.***>
Cc: ManStu ***@***.***>; Author ***@***.***>
Betreff: Re: [fuzzylite/pyfuzzylite] Questions to create a TSK model (Issue #75)


Hi

Thanks for your post.

(1) Numpy is now used across the library, and its main component is the array (np.array), but you should be getting a unit array, ie with a single value.

(2) I think the nan values are because you set the input value of only one input variable when you have two. The default input value is nan, which propagates. If you set the other variable's value you should see what you expect.

Let me know if this solves your issues.

Cheers

-

**Comment by jcrada** [comment]
Hi,

It's a bit hard to help without seeing the code, inputs and outputs. If you like, share a Google Collab notebook showing what you are getting and what you expect?

**Comment by ManStu** [comment]
Hi,
here the link to Colab-Notebook: https://colab.research.google.com/drive/1cCoNJej3JEFWGDIY5sED-lNBZgiGm1xk?usp=sharing

Thank you

**Comment by jcrada** [comment]
Hi, I don't have permissions to access the notebook.

**Comment by ManStu** [comment]
Excuse me. The access rights have now been adjusted. :-)

**Comment by jcrada** [comment]
Hi, there is a bug in `engine.input_values`. If you check the notebook, you will find out how to make it work.

Many thanks for reporting this. I will fix the bug as soon as I have the time and release a new version.

**Comment by jcrada** [comment]
This bug has been fixed in `8.0.2`. Many thanks for reporting.

**Comment by ManStu** [comment]
Thank you very much for the super fast response and problem solving.

Von: Juan Rada-Vilela ***@***.***>
Gesendet: Freitag, 26. April 2024 05:56
An: fuzzylite/pyfuzzylite ***@***.***>
Cc: ManStu ***@***.***>; Author ***@***.***>
Betreff: Re: [fuzzylite/pyfuzzylite] Questions to create a TSK model (Issue #75)


This bug has been fixed in 8.0.2. Many thanks for reporting.
